-- 0020_abtest: A/B 实验分流框架（M3-OPS-03）
CREATE TABLE experiment (
  id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(64)  NOT NULL COMMENT '实验名称',
  target     VARCHAR(32)  NOT NULL COMMENT '应用场景：recommend 等',
  variant_a  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'A 组策略标识',
  variant_b  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'B 组策略标识',
  ratio      TINYINT      NOT NULL DEFAULT 50 COMMENT 'B 组流量占比 0-100',
  status     TINYINT      NOT NULL DEFAULT 0 COMMENT '0启用 1停用',
  remark     VARCHAR(200) NOT NULL DEFAULT '' COMMENT '说明',
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='A/B 实验（按用户哈希分流）';
